# Generated by Django 4.1.7 on 2023-04-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['date_published'], name='app_book_date_pu_686eda_idx'),
        ),
    ]
